version: '3.8'

networks:
  llm_network:
    driver: bridge

services:

  llm_wx:
    build:
      context: .
    container_name: llm_wx
    networks:
      - llm_network
    ports:
      - "8081:8081" # 根据你的 Java 应用的实际端口进行调整
    depends_on:
      - kafka
      - redis
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATA_REDIS_HOST=redis

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    restart: always
    networks:
      - llm_network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    restart: always
    networks:
      - llm_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    expose:
      - "2181"

  redis:
    image: redis:alpine # 使用最新的 Redis 镜像
    container_name: redis
    networks:
      - llm_network
    ports:
      - "6379:6379"